### ISSUE TITLE
WGIPS HERAS request for format change - Add optional unit 'winter rings' for Biology.Age

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/wg_WGAcousticGov#1]
WGIPS HERAS request an option to express Biology.Age in winter rings in addition to the current fixed unit of years which is appropriate for Herrings in the HERAS survey.

**Comment by SMLusseau** [comment]
Maybe I misunderstand the text, but it is not "optional" to upload in winterrings for the HERAS survey. It is mandatory. What we need is to be able to tag the age data with a unit similarly to how weight and lengths are treated where you specify the unit in a separate field to avoid confusion.

**Comment by CiaranOD** [comment]
Requirement for age field to be accompanied by option field of age in yrs or in winter rings.  All herring reported as winter rings as a requirement for HAWG. Need to clarify if this is the case for Baltic herring also. If so then all herring are in winter rings and not years.

**Comment by CiaranOD** [comment]
It was agreed during WGIPS (Jan, 2021) that provision will be made for the inclusion within the biotic file format age field for the reporting of herring as winter rings (wr) as required for international reporting to the assessment groups (HAWG) @HjalteParner

**Comment by HjalteParner** [comment]
Currently it has been decided to add an additional mandatory field AgeUnit as a vocabulary initial with Years and Winter Rings as terms. 

However Jan Arge suggested that we instead could add an additional optional field called WinterRings and skip the AgeUnit vocabulary all together.

This will enable us to differentiate between autumn spawners i.e. Age: 2 Years, WinterRings: 1 and spring spawners i.e. Age 1, WinterRings: 1.

In addition this solution i.e. having an optional field won't affect any data submitters not needing this information.

@SMLusseau, how does this sounds?

**Comment by SMLusseau** [comment]
@HjalteParner, This will not work if you make it mandatory. For herring you can only provide the age in years if you have assessed it to be a spring or autumn spawner (or winter or summer spawner for that matter....). You can always provide age in winter rings as this is the unit that the age is observed in. Age in years is a derived metric for these fish, not an observed one. I am a great believer in only storing observed data in a database, not derived, guessed or otherwise manipulated to the best of our ability.
There is a separat issue to this and it is herring where the age is read from scales rather than otoliths (Norwegian Spring Spawning herring) . It would be helpful if this can be flagged in the database too. In the IESNS both methods are used for aging herring depending on the institute doing the aging. There are plans to look at the relationship between the two methods and if you have a record of the method used to derive the age corrections can be applied in post processing if this is deemed relevant.
Seems this is not such a straight forward issue to solve after all :-)

**Comment by HjalteParner** [comment]
@SMLusseau I would leave both the Age and (Winter)Rings as optional. So for your herrings you can choose just to use the (Winter)Rings field and leave the Age empty. Jan Arge can choose to fill both if that makes sense to his survey. My question would be if the name WinterRings indeed would be right term to use or if it rather just should be called 'Rings'?  

I agree that we should keep observed data in the database and not derived ones.

I guess the existing field AgeSource exactly gives you the opportunity to tell if scale or otoliths where used i.e. http://vocab.ices.dk/?ref=1482

**Comment by sindrevatnehol** [comment]
Dear all. 

I share @HjalteParner question if WinterRing is the correct terminology. I think it should be more general and not "season" based. 
I am not a biologist, but I have seen the term Growt Rings being used (is this the same as the "winter rings"?) 

One related but a different topic. 
For NSSHerring we measure the size of the "growt" rings from scales to back calculate the age of first spawning per individ, and use this to estimate the maturity ogive. 
I do not see that such information is avaliable in the current format. 
But before presenting this as a new issue, I need to investigate if this is one-species solution and to work on the documentation.

**Comment by HjalteParner** [comment]
@SMLusseau do you have any final comments to latest elaboration by me?

**Comment by SMLusseau** [comment]
Hi Hjalte, I think this is a good solution. With regards to the terminology I dont have any strong feelings about winter or growth rings. They are the same. Cheers, Susan


________________________________

**Comment by odontaster** [comment]
Hi @HjalteParner I think this addition 
//vocab.ices.dk/?ref=1482
needs to go through RMG, but it looks quite fine.

**Comment by HjalteParner** [comment]
Done
