### ISSUE TITLE
Partial Reporting - Is this problematic and if so what to do?

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/wg_WGAcousticGov#11]
When reporting acoustic and biotic data into the acoustic trawl data portal, often only the target species are reported. This is problematic for future analysis and assessment as the submissions doesn’t give the full picture and the rest of the data might potential be lost for the future.

**Comment by SMLusseau** [comment]
I think this is only problematic if it is not made clear what is uploaded for each survey/cruise. 
If a cruise is targeting herring, it will definitely be scrutinized for herring but you should not expect to find acoustic data uploaded for Blue Whiting for example even if it may occur in the survey area at the time. There is an additional cost involved for every species you determine to be a target of a survey and if it is not a target of the survey the evidence you have collected to base you scrutiny descisions on will be less certain than for your targeted species. The scrutiny process itself takes extra time for each species added, but there are also implications at the execution stage. Unless your extra species are always  found in mixed aggregations with your target species additional trawling and biological data collection is required for ground truthing the acoustic aggregations assigned to the species and for biological information on this species to be representative of the species in the area.
For example in the herring survey we see blue whiting and mackerel, but because they are distinctly different from herring acoustically, trawling will not be carried out on these unless there is a need to verify they are not herring (or the national cruise is also targeting these as some are). As a result the biological information on Blue Whiting and Mackerel in such a survey will be incidental catches and not necessarily representative of the Blue whiting and Mackerel in the area at the time. That is more dangerous in my opinion if someone down the line decides that since the data is in the database it must be of good quality.
For strictly biological data I think it is safe to upload all the data as long as it is treated as confirming presence only of all other than the target species. There may not always be time to identify and measure all other components of the catch to species level, so absence means it was not reported, whereas if they are reported they were clearly there. For the target species however, a haul without herring on a survey targeting herring can be assumed as a "true" absence of herring (or at least an inability to catch them).
I think the solution here is to make it clear what to expect to find under each survey that is in the database and what agreements have been made on uploads each year for each component cruise. That way if you wanted you can also add certainty tags to the acoustic data uploaded if you really want to have this less certain and less reliably scrutinised for data uploaded.

**Comment by CiaranOD** [comment]
I have contacted the chairs of WGIPS to ask that this be discussed at the next meeting in January. I think this is best addressed by the wider group for consideration

**Comment by CiaranOD** [comment]
During WGIPS this issue was discussed further. Target species (biotic and acoustic reporting) and non-target species (inconsistent biotic and acoustic reporting) are detailed at the survey report level (WGIPS report and national online report repositories). However, for those who may access and download the data via the portal, this may not be clear. It is therefore important to make it clear so incorrect assumptions are not made about the presence/absence of non-target species in the data. 

It was agreed that this point would be highlighted to alert the data user at the point of download on the terms of acceptance page:

![2021-01-21 07_49_27-ICES Acoustic-Browse Submissions](https://user-images.githubusercontent.com/9465738/105319800-48027800-5bbd-11eb-87a9-892a2a05b07a.jpg)

@CiaranOD will formulate some text to be included.
