### ISSUE TITLE
acoustic DB format for length frequency

### ISSUE THREAD

**Issue by bberges** [ices-eg/wg_WGAcousticGov#12]
With biological data there is commonly two sampling processes for each sample haul: the sampling onboard with length frequency and catch composition and further biological processing (age, maturity, weight, length) of selected individuals (e.g. 5 individuals per 0.5 cm bins). In order to produce StoX outputs *.xml, it is necessary to have individuals in the Biology section for both age sampling but also added ones to best represent length frequency. Though, as defined by the ICES DB format, length frequency should be given in the Catch section of the Biotic file, separately from the Biology section.

This results in an inconsistency in the ICES DB biotic data format or at least a miss specification on where the length frequency data should be included.

Enclosed are two files that exemplify the issue:
- Biotic_2020_NL_HERAS2020_20201113.csv: file with length frequency in the catch section, submitted following ICES DB format but potentially not compatible for correct StoX *.xml ouputs
- Biotic_NLHERAS2020.csv: file with added individuals in the Biology section.
[Biotic_NLHERAS2020.txt](https://github.com/ices-eg/wg_WGACOUSTICGOV/files/5798812/Biotic_NLHERAS2020.txt)
[Biotic_2020_NL_HERAS2020_20201113.txt](https://github.com/ices-eg/wg_WGACOUSTICGOV/files/5798813/Biotic_2020_NL_HERAS2020_20201113.txt)

**Comment by CiaranOD** [comment]
This issue was discussed at WGIPS (Jan, 2021) and will be considered within an upcoming review of biological sampling strategies used within WGIPS. A recommendation from HAWG to investigate inconsistencies of cohort tracking for older (>wr) age cohorts of herring within the HERAS survey has been taken onboard by WGIPS as a new ToR for the coming 3-year cycle. With support from the wider WGIPS group, this will be broadened to include all surveys reporting to the DB. The issue highlighted is important in that it has implications not only for the way fish are sampled on-survey but also how they are stored and ultimately how they are weighted in the final estimate of abundance.  

First steps to address:
Within ICES, @HjalteParner will discuss the issue with the StoX team with input from @bberges as required. 
Within WGIPS, the development of the new ToR will see this larger issue actioned.

**Comment by CiaranOD** [comment]
Hi @bberges,

We had Espen here at the meeting today and he was enquiring if you were using the new version of StoX (R) and the ICES XML from the ICES DB. Espen is happy to discuss this issue with you further if you want to contact him.

**Comment by odontaster** [comment]
https://github.com/ices-eg/wg_WGACOUSTICGOV/issues/40
