### ISSUE TITLE
Check acoustic files are sorted by log distance?

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/wg_WGAcousticGov#17]
After DE upload of BASS survey 2020 - LogDistance was wrong and it went through anyway making the map look like this: 

![image](https://user-images.githubusercontent.com/23259812/109163030-2aef3500-7779-11eb-994a-d2aa364f2bad.png)

Acoustic files are stored as received. Should we add check to enforce that acoustic files are sorted by log distance?

Should we also check acoustic log distance increases with with log time?

**Comment by HjalteParner** [comment]
Implemented - submitted acoustic files doesn't need to be sorted in order to validate, however a check have been added to make sure log distance increase with log time.

**Comment by Mackinson** [comment]
Inconsistency reporting ‘Log Distance should increase with Log Time '2020-09-02T23:57:00'.
The assumption that the log distance will increase at all times is correct. It is not however correct that Log time should increase with log distance because of the way transects can be sequenced during processing. As implemented, the rule that log time should increase with log distance is incorrectly picking up faults that are real. The simple rule should be that log distance should increase. It two do not need to be contingent on one another.
