### ISSUE TITLE
Inconsistent format description in the Acoustic

### ISSUE THREAD

**Issue by sindrevatnehol** [ices-eg/wg_WGAcousticGov#19]
Sometimes users do not interpretate all the acoustic data. Using the sandeel as a case (but this is common on other surveys), only the acoustic scatterers that is interpretated as sandeel (or the main species) are stored. Data without the main species are left unclassified instead of using the other categories such as UKN category. Such strategies will produce empty LOG field in the XML file when using LSSS; i.e. no SAMPLE information is available within the LOG field. After an evaluation we found an inconsistent regarding the minimum allowed number of samples in the LOG field. Regarding that some users leaves some data unclassified; we also need to evaluate how this should be handled. 
	
LSSS uses the XSD schema that is downloaded from ICES. The requirement from XSD schema for the SAMPLE field states: 
<xsd:element name="Sample" type="Sample" minOccurs="0" maxOccurs="unbounded"/>
I.e. The number of samples within the LOG field can be 0. 

But several has experienced when submitting to the ICES databases that empty LOG fields is not allowed and an error msg is reported. Hence, minOccurs =1 is apparently a requirement during submission. This is consistent with the EXCEL description of the format the SAMPLES is labeled as mandatory, but not with the XSD schema. To obtain a successful upload, these empty LOG fields must be removed or filled.  

In StoX, a future release will require that a LOG field exist,  but the SAMPLE can be missing. It is thus interpretated that the vessel has been in an area, but no scatterers of interest was within this distance. The Sv value for this distance is thus assumed to be 0 for the relevant species. 

Therefore, StoX can use data directly from LSSS but will produce a different estimate if the data has been downloaded via ICES and empty LOG fields has been removed before submission.

Proposal: 
•	The minOccurs is kept being 0 in the XSD schema, but the EXCEL description and the requirement in ICES acoustic DB is updated to be consistent with the XSD schema.

**Comment by HjalteParner** [comment]
Sindre, I think we might have made a mistake here in the acoustic xsd in January this year where we made the sample optional instead of mandatory. FYI it was done at the same time where catch was made optional in relation to haul in the biotic xsd as you can have a haul without catch. However, I'm not sure the same should logically be true for sample in relation to log as you should (in my opinion) always register what you have investigated. So if you should as such (in my opinion again) make a record for each layer you have sampled and then record 0 in the data record for the target species and possible also a value (which might be 0)  for UNK for the rest of the acoustic backscatter signal you haven't classified into a category. If you do not give a sample/data for a given layer, then it's impossible know whether you just haven't looked in that (which) layer or if you just didn't bother to report your findings. In other words, I'm not a fan of assumptions as I don’t know how to interpret these unwritten assumptions!

**Comment by sindrevatnehol** [comment]
Hi Hjalte. The way I like to interpretate I follow your opinion excatly! But others may not share that strategy so I think it is better to have a discussions what requierements the database should have. 

But perhaps there is a need for a easy acces description of the requierements for the database that does not fit in the XSD? We get these logic errors when we submitt, but it would be nice to have them avaliable before. Perhaps within the same zip file when we download the format description?

**Comment by HjalteParner** [comment]
Sindre, yes I agree. We should definitely improve the format description in addition to the hardcoded schemes and validation rules. Do you volunteer ;-)

**Comment by sindrevatnehol** [comment]
Hjalte. If you send me list of all the database requierements (i don't have a overview of everything...) I can make a description and make an issue to WGACOUSTICGOV for approval when finnished.

**Comment by HjalteParner** [comment]
@HjalteParner check that xsd have been changed and then close

**Comment by HjalteParner** [comment]
We did investigate how things are currently according to the acoustic xsd.

Currently you are allowed to have a Log without a Sample but a given Sample need to have Data. So no assumptions! If you don't find any signal for a given sample (layer) then you need to record a 0 value for Data. You can do this for UNK or/and your target species if you like.

Is this fine for you @sindrevatnehol ?
