### ISSUE TITLE
Validate vocabulary entries

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/wg_WGAcousticGov#2]
Entries in the acoustic vocabularies https://vocab.ices.dk/?theme=4 used in the acoustic format are based on the WGFAST metadata convention for processed acoustic data while the biotic counterpart vocabulary entries are based on the DATRAS format with a few additional cross boundaries common vocabularies. The current vocabularies entries needs to be validated and we need to find a way to govern these vocabularies entries looking ahead.

**Comment by CiaranOD** [comment]
I will make contact with DATRAS chair to start this process ahead of our next meeting

**Comment by odontaster** [comment]
Hi both @HjalteParner  and @CiaranOD.
Since this issue was opened there has been a change on how vocabs are managed throughout ICES databases. In order to try to keep them as consistent as possible, all vocab changes and addittions should go to the Reference Management Group 
https://github.com/ices-eg/DIG/projects/2
where a group of data managers will check requests, approve, ask for clarifications, etc and provide quick answer as required.
