### ISSUE TITLE
Catch sub-sampling PELTIC 

### ISSUE THREAD

**Issue by Fabio-Campanella** [ices-eg/wg_WGAcousticGov#20]
The catch sub-sampling procedure on the PELTIC survey is quite complex and it cannot be fully captured in the current format of the ICES database and consequently within StoX. 
Here some of the main points summarised:

•	The subsampling of the total catch is done by categories that are primarily based on size. The categorization is done visually while sorting the catch.
•	The subsampling can be made of a single species or a mixed of species depending on volume fish caught within a station. A species can be part of different size categories and the different length frequencies of the different categories can overlap at the extremes
•	No weight per length class which means assumed mean weight for that length class using individual fish data if collected or Length/Weight relationship estimated from the survey.
•	At the end, once species (total catch or subsample) have been measured, system raises automatically to raised numbers at length, also providing the actual measured number of fish per length within a category. 
•	Biological data on our system does not relate to categories, it is based on overall otolith targets made per station (as below).
•	Otolith target depends on size category. Medium/large individuals have more otoliths taken (e.g. 5 per length class); small individuals have less otoliths taken (e.g. 2 per length class).

The main issue is that we don’t have a subsample weight, number and LFD but only the ones raised to the total catch. We have tried to use those instead of the subsample in StoX resulting in a crash of the software (very large individual table). We ended up using a “fake” fixed subsample (e.g. 1000 individuals for when numbers are higher than a 1000 at a given station) for all the species which it does the work but it’s not ideal.

**Comment by HjalteParner** [comment]
Fabio, I think your description of your current sampling strategy and your difficulties with the format is a very good starting point for getting a description of all the different sample strategies out there in order to evaluate the current biotic format i.e. is it sufficient or possible could it be made more suitable and intuitive with appropriate adjustment. It might also be that the diverse sampling strategies presumably out there could be made more standardised - or a combination thereof - all for the benefit of the abundance estimations, assessments and in the end final advice making these as streamlined and transparent as possible. In my view do this valuable exercise under the thesis “Problems can be complicated - Solutions cannot”.

**Comment by HjalteParner** [comment]
[
[01_BioticWith_Weight.xlsx](https://github.com/ices-eg/wg_WGACOUSTICGOV/files/6516790/01_BioticWith_Weight.xlsx)
[02_BioticWith_LengthDistribution.xlsx](https://github.com/ices-eg/wg_WGACOUSTICGOV/files/6516792/02_BioticWith_LengthDistribution.xlsx)
[03_BioticWith_CatchSpeciesCategory_LengthDistribution.xlsx](https://github.com/ices-eg/wg_WGACOUSTICGOV/files/6516793/03_BioticWith_CatchSpeciesCategory_LengthDistribution.xlsx)


](url)

**Comment by CiaranOD** [comment]
To be raised as part of larger Biological sampling strategy review to be discussed at WGIPS in Jan 2023. Ciaran O'D to update.

**Comment by odontaster** [comment]
https://github.com/ices-eg/wg_WGACOUSTICGOV/issues/40
