### ISSUE TITLE
38 kHz beam angle?

### ISSUE THREAD

**Issue by elorsepp** [ices-eg/wg_WGAcousticGov#29]
Hello

We have encountered a question in our WG concerning using other beam angles than the 7 degrees stated in the manual. Since the new Simrad 38kHz 7 degrees is rather large and heavy, it is not comfortable for portable use. What are your expert opinions/knowledge about the possibility to use 10 or 18 degrees instead of 7? Does it implement any biases that should be considered? Could we allow it?

I apologise if that is a stupid question, but when the survey manuals were originally compiled, I was not around yet and could not find the reasoning behind allowing only 7 degrees in (our WGBIFS) manual.

Best regards
Elor Sepp

**Comment by jmjech** [comment]
There is no fundamental reason why one beam angle can/should be used over another. But there are tradeoffs.

A wider beam will sample more water but is harder to use for target strength (TS) measurements. A narrow beam samples less water but can be useful for TS measurements. A "narrow" beam angle, such as 7 degree, is commonly used now because it seems to be a good compromise between sampling enough water for volume scattering (Sv) measurements that are used for surveys and restricting targets for TS measurements.  

The beam angle is used to standardize the Sv measurements to 1 cubic meter, so in theory one can compare Sv measured by a 7-degree beam to Sv measured by an 11-degree beam. However, the spatial distribution of the animals will also influence Sv. A wider beam will sample more water and potentially sample more animals at ranges close to the transducer compared to a narrower beam. This effect can be magnified by the speed of the platform, i.e., a wide beam will have smaller gaps than a narrow beam at short ranges.

So, to make comparisons "easy", using the same beam width among transducers potentially removes a confounding factor. But, I agree that the logistics of putting a large, heavy transducer on smaller platforms (e.g., autonomous underwater or surface vehicles) is often not possible, so accommodations will be required.

**Comment by jmjech** [comment]
One more comment that I just ran into. I was attempting to do dB-differencing between data collected with a combination transducer with a 21 degree beam 38 kHz and 7 degree beam 200 kHz, and it was nearly impossible to get anything useful. Even though the beam axes are next to each other, the sampling volumes are so different that animals detected in the 21 degree beam are not necessarily detected by the 7 degree beam, and the assumptions that they are sampling the same volumes and same animals are violated. This doesn't necessarily preclude comparing Sv from each, but care must be used.

**Comment by CiaranOD** [comment]
Resolved, yes, no, but maybe.....
