### ISSUE TITLE
Direct link to ICES database in StoX

### ISSUE THREAD

**Issue by elorsepp** [ices-eg/wg_WGAcousticGov#34]
Is there a possibility to add direct browsing/downloading/opening option to StoX program. Currently the downloading-unzipping-copying to correct folder takes time and seems unnecessary.

**Comment by CiaranOD** [comment]
Hjalte- can provide the details. Can trial with Stefanie Shiny App and connectivity to ICES DB. TAF example file provided by Hjalte: https://github.com/ices-taf/2021_boc.27.6-8_acousticIndex

Espen-Import process not too taxing as it is. Small software program could link to the DB and conduct the download to the specific input folder in the StoX program. Could be a toolbox application

Mike- Issue if data within the DB changes and is no longer valid for the StoX. 
Espen- Importing File App rather than directly reading from the DB. 
Espen- Would like to see the version of the data missing from the ICES DB file e.g. when the data was uploaded.  

### Hjalte will assist Stefanie to link up her App to the ICES DB as a first trial. Small software program could link to the DB and conduct the download to the specific input folder in the StoX program. Could be a toolbox application. This will not be a direct live link but more to facilitate a one-time file download to StoX project folder.

**Comment by HjalteParner** [comment]
Seems like there's only a nice to have interest in this feature
