### ISSUE TITLE
IMR request for format change - Add optional possition to accommodate acoustic data from drones and the like

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/wg_WGAcousticGov#6]
Dear Hjalte and Ciaran

As far as I understand, the responsibility to maintain the IcesAcousticFormat (acoustic.ices.dk) is now under the WGAcousticGov. 

Last year Hjalte and people at IMR had a discussion regarding adding a stop/end position to each log distance (see attached conversation) 

I just got the information that CCAMLAR and people using drone-technology want to move forward to use the ICESacousticFormat as an official output, and they address a great need for this extra position.  
I should also mention there is a great interest of using drone-technology on several of the acoustic surveys connected to ICES assessments. 

To summarise the issue:
On acoustic surveys, the log distance (i.e. 1 nmi) is use to weight the data along a transect when estimating the abundance indices. The assumption is that the vessel is moving in a straight line. 
In CCAMLAR and for drone-technology, the vessel may not move in a straight line all the time due to icebergs, wind conditions, etc (see the free hand drawing underneath, black is the planned route and red is the “actual” vessel route)

![imr-track](https://user-images.githubusercontent.com/23259812/101158787-a040e300-362c-11eb-9510-dbb57bc49db4.png)

If the log distance is used uncorrected, as far as I understand, the estimation of any fish abundance in the left of the figure will have higher weight in the assessment then what is observed in the right due to the fact that the left side will then have more data.

CCMLAR has found a solution for this, where they compute an effective log-distance using the start/stop location of each log distance compared to the start/stop location of the transect. 
Unfortunately, the data is not necessary continuous due to excluding region where we have i.e. trawling. Otherwise we could have used the start position of the next log distance as the stop position.

To prepare the ICESacousticFormat to be used for abundance estimation in the scenario as described, it was proposed to add three new variables in the format description seen underneath ( indicating Latitude, Longitude and Log Origin for the stop position as a conditional mandatory variable)

![imr-format-change](https://user-images.githubusercontent.com/23259812/101158855-bea6de80-362c-11eb-89d8-840a1f58ea49.png) 

I initially planned to wait with this input until after the startup of the WGAcousticCov, but there is a urgent need to get this defined and implemented. 
Therefore I am reaching out to you now with this request. 

As far as I understand, we need to figure out a naming of the three variables. (i.e. Longitude2, LongitudeSupliment, or others) that is not confusing and can be implemented in the system that is already in place. 
Using a conditional mandatory for these variables will ensure that the data submitters don’t have to resubmit the data.

Hjalte has a better overview of the technical difficulties, so please address this if needed. 

Hopefully we can start this discussion even though there has not been an official startup of the WG, and perhaps we can include the other members of the WGAcousticGov. (I don’t have this list of members). 
Please let me know if I have been to vague in the problem description. 

Best regards, 
Sindre Vatnehol (PhD) 
Scientist
Pelagic Fish Group
Institute of Marine Research 
Bergen, Norway
www.hi.no

**Comment by CiaranOD** [comment]
Sindre to contact Espen Johnsen (StoX) and CCAMLAR rep to provide more detail.

**Comment by CiaranOD** [comment]
I received the documentation from Gavin et al. and Mike has kindly agreed to have a look. 

[emm-16-38.pdf](https://github.com/ices-eg/wg_WGACOUSTICGOV/files/5687917/emm-16-38.pdf)
[off-transect-correction.pdf](https://github.com/ices-eg/wg_WGACOUSTICGOV/files/5687919/off-transect-correction.pdf)

**Comment by CiaranOD** [comment]
Mike Kindly agreed to have a look at this request and has raised some alternative options: 

Hi Ciaran,
Thanks for the material. I see the need for the weighting of each ESU and the method they propose is sound. 
 
The remaining question is whether there is a need to add another data point with three new variables to define the ESU. Figure 3 in Gavin's document shows why the start point of an ESU can not be used for the end point of the immediately prior ESU. In some cases there is a gap in the transect coverage due to trawling or other activities. I can envision a few different ways to deal with that without adding three more variables, but the most appropriate seems to use the existing "LogDistance" variable. If I understand the data table correctly, each data value (presumably sA) for each ESU has LogLatitude, LogLongitude, LogOrigin, and LogDistance associated with it.  It seems that the LogDistance may be automatically filled for all ESUs, but I don't think it needs to be that way. The data could be entered as
1. Apply the weighted distance correction prior to entering the data, and leave the LogDistance = X (whatever is the standard for that survey, e.g., 1, 0.5, etc...), or
2. Modify the LogDistance for each ESU.
If the downstream calculations include multiplying by the LogDistance, then 1 or 2 will work without having to add three more fields. For example, if each ESU was distance weighted prior to entry, then they have been scaled to whatever the standard survey ESU distance is and calculations can go on as before. I think #2 will only work if the downstream calculations include a way to incorporate a dynamic LogDistance.
 
Is that a suitable solution?
 
All in all, I'm not against adding three more variables, but it seems that there is a way to work with the table as it is now.
 
Let me know if there is more discussion.
Best,
mike

**Comment by CiaranOD** [comment]
I contacted Gavin to request their group consider the options from Mike's review. I will upload the response when we get it. The best outcome would be to have the inclusion of this new user group without the disruption of the existing Acoustic input file format. Looking forward to more discussion on this. 

####### STARTS######
Hi Gavin and others,

I hope this email finds you well. 

Thanks for the document this was helpful in adding further background to the request and my apologies for the late response, entirely my fault. 

Mike (cc’d) kindly took on the task of reviewing the request and I enclose his comments for your consideration. It looks as though there could be an option to retain the existing acoustic file format ? For the wider user group, this would be the path of least resistance given the number of current users. Obviously, we will always work towards the inclusion of new members and if we can do this with the least disruption to file formats all the better. To that end, I would ask if you could please review Mike’s comments and explore this option. 

Looking forward to your response.  

Kind regards,

Ciaran

####### ENDS######

**Comment by sindrevatnehol** [comment]
Both of Mike's suggestions mean doing the data manipulation and correction calculation prior to storage in the ICES Acoustic database. We suggest that this is the more important decision to make: is the calculation better (or more easily) done prior to producing the ICES acoustic format files or after? The calculation requires knowledge of the intended transect path - is this more readily provided to the software that produces the ICES files or to the software that reads the ICES files? More practically, should programs like LSSS and Echoview do the calculations or should programs like StoX do the calculations? 
 
Another important consideration is transparency of acoustic processing steps. For example:
- altering the meaning of the log distance would require a flag of some sort in the ICES Acoustic format to explain the meaning of 'log distance'. 
- NASC has a definition that is independent of the corresponding distance measure. Incorporating the off transect correction into the NASC renders the NASC value unreliable if the user is not aware of that modification.
 
Incorporating the correction into NASC or log distance would be a significant change to the current meaning of the fields in the ICES Acoustic data format, whereas adding the end position has the distinct advantage of not modifying the meaning of existing fields in the file format and hence would be a more 'backward compatible' change to the format. This also lets the biomass estimation software make the choice of whether to apply, or not apply, an off transect correction.
 
We are strongly in support of making the correction during the survey estimation calculations, and we cannot see any other solution that will solve the transparency and flexibility needed for various survey designs and survey estimation methods. Therefore, we recommend to include the needed variables in the ICESacoustic.XML format.
 
All the best,
Sindre, Gavin, Espen, Arne Johannes and Georg

**Comment by HjalteParner** [comment]
I tend to agree with the Norwegians on keeping the data as raw as possible and do the calculations in the abundance estimation software.

One way would be to add as suggested a LogLatitude2, LogLongitude2 and LogOrigin2 as optional fields. However if its actual the traveled distance we are after to make the correction where needed, then we could perhaps just add an optional LogDistanceTraveled field instead?

**Comment by sindrevatnehol** [comment]
As far as I can read from document from Gavin, I do think that using an optional LogDistanceTraveled would contain the information needed. But, this will require some changes in the different softwares and that the users, while interpreting the acoustic data, add information of the start and stop of each transect. Not sure if this is practical during the interpretation, but it can be discussed. 

But to toss inn another solution. 
If LogLatitude, LogLongitude and LogOrigin are allowed to become vectors, then start and stop position of each logDistance can be available without the need of specifying new optionals fields. Do you believe this solution is feasible?

**Comment by HjalteParner** [comment]
I'm not exactly sure how to do this in a smart way! Then I will vote for the simple solution of adding the initial suggested LogLatitude2, LogLongitude2 and LogOrigin2 as optional fields.

**Comment by jmjech** [comment]
I'm not averse to adding the new variables, I just wanted to make sure that is the most efficient and understandable way by all involved. Since I am not a user of these data, I am ignorant of the procedures used before and after the data get entered into the database, so I don't understand all the nuances of the different software packages used to process, ingest, and then calculate an abundance estimate. It seems from the arguments by the Norwegians that adding the three new variables is the solution, and I am fine with that. 

I will advocate that this change is described to all who enter data into this database and to all who use it.

**Comment by HjalteParner** [comment]
Thanks @jmjech, one never knows...you might want to make use of ICES acoustic trawl data portal at some point in the US as well. You are at least welcome to do so at any time!

**Comment by jmjech** [comment]
I actually have thought of that, @HjalteParner. We aren't doing any dedicated acoustic surveys any longer, but we are collecting acoustic data during our bottom trawl surveys, and those data are being used in the Atlantic herring assessment. So I may revisit that thought. Thanks for the invitation!

**Comment by CiaranOD** [comment]
Three extra optional fields are to be added to accommodate this request

**Comment by HjalteParner** [comment]
Done
