### ISSUE TITLE
Survey Areas - how to deal with these?

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/wg_WGAcousticGov#9]
Each survey have an error defined for the given survey. When data are submitted they get validated against the given survey area and buffer zone around the survey area and gets an error or warning if outside the survey area or buffer zone respectively. An error prevents the data from being uploaded.
This is not optimal at the idea behind the acoustic database is to keep cruise data together and as such not delete these data if outside the survey area, to get the data into the portal. A fix has been made to set a validity flag for either the acoustic and/or the biotic part of the data which will enable these data to get in. However the validity flag is not specifically minded on this but could also be used fx. to flag a broken trawl. Likewise the data might indeed be valid and just outside the survey area and even a warning is misleading. We need to revise this!

**Comment by CiaranOD** [comment]
Feedback from the group was that the boundary buffer and warning (<10Km from baseline) and critical error (>10km) should remain and the emphasis is on the data submitter to check and validate

**Comment by SMLusseau** [comment]
Sorry - maybe I misunderstood completely then. Was it not nothing happens if a data point is within the buffer, and we get a warning only outside the buffer so the data can be checked and validated by the submitter before proceeding to upload?

**Comment by CiaranOD** [comment]
The outcome of discussions at WGIPS (Jan, 2021) was that data values submitted that occur either outside the geographical baselines of the survey area and the applied buffer zone (10Km) would result in a warning to the data point rather than an error. This will be implemented in the DB @HjalteParner The emphasis would then be on the data submitter to check their data and correct if required. Data points outside of boundaries and buffer zones may reflect year specific on-survey instances.

**Comment by HjalteParner** [comment]
Implemented
